### ISSUE TITLE
change design on church admin

### ISSUE THREAD

**Issue by modiglianicerda** [asaph26/ca-issues#6]
Would be nice with same design on church admin as the rest, but even more important. 
Blue colour on the pics and instead of a arena for connect group we should have pictures of people rather than a arena.

**Comment by asaph26** [comment]
This is in progress. Key things would be
- [x] The images will be replaced with icons as there are other apps that are built.
- [x] We will have a gradient free setup similar to the other apps

**Comment by asaph26** [comment]
This is resolved and released
